---
abstract: 'leader board using Redis'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  Test::More: 0.98
  Test::RedisServer: 0
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Redis-LeaderBoard
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Redis::LeaderBoard:
    file: lib/Redis/LeaderBoard.pm
    version: 0.03
  Redis::LeaderBoard::Member:
    file: lib/Redis/LeaderBoard/Member.pm
recommends:
  Redis::Fast: 0
requires:
  Mouse: 0
  Redis: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/Songmu/p5-Redis-LeaderBoard/issues
  homepage: https://github.com/Songmu/p5-Redis-LeaderBoard
  repository: git://github.com/Songmu/p5-Redis-LeaderBoard.git
version: 0.03
